/*
  1. For easy remebering the names
  2. For auto-completion in the IDE
*/
export const designRecipes = {
  modalOverlay: "ds-modal-overlay",
  modalContainer: "ds-modal-container",
  modalHeader: "ds-modal-header",
  inputBase: "ds-input",
  inputError: "ds-input-error",
  buttonPrimary: "ds-btn-primary",
  buttonSecondary: "ds-btn-secondary",
  iconButton: "ds-icon-btn",
  panel: "ds-panel",
  topbarShell: "ds-topbar-shell",
  navItemBase: "ds-nav-item-base",
  navItemActive: "ds-nav-item-active",
  navItemIdle: "ds-nav-item-idle",
  badgeDanger: "ds-badge-danger",
  statusSuccess: "ds-status-success",
  statusWarning: "ds-status-warning",
  statusDanger: "ds-status-danger",
  authFormShell: "ds-auth-form-shell",
  authFormContent: "ds-auth-form-content",
  authDecorBlurTop: "ds-auth-decor-top",
  authDecorBlurBottom: "ds-auth-decor-bottom",
  inputWithIcon: "ds-input-icon",
  formLabel: "ds-form-label",
  formError: "ds-form-error",
  buttonSubmitFull: "ds-btn-submit-full",
  linkBrand: "ds-link-brand",
  authDivider: "ds-auth-divider",
  authSplitLayout: "ds-auth-split",
  authSplitCarouselCol: "ds-auth-split-carousel",
  authSplitFormCol: "ds-auth-split-form",
  profileHeaderCard: "ds-profile-header-card",
  profileBioCard: "ds-profile-bio-card",
  profileCover: "ds-profile-cover",
  profileCoverGradient: "ds-profile-cover-gradient",
  profileAvatar: "ds-profile-avatar",
  profileEditIconBtn: "ds-profile-edit-icon-btn",
  profileCoverEditBtn: "ds-profile-cover-edit-btn",
  profileMetaEditBtn: "ds-profile-meta-edit-btn",
  compactBtnPrimary: "ds-btn-compact-primary",
  compactBtnWarning: "ds-btn-compact-warning",
  compactBtnReport: "ds-btn-compact-report",
  compactStatusSuccess: "ds-status-success",
  compactIcon: "ds-compact-icon",
  pageShell: "ds-page-shell",
  pageCenter: "ds-page-center",
  pageContainer: "ds-page-container",
  pageContainerWide: "ds-page-container-wide",
  panelHover: "ds-panel-hover",
  panelList: "ds-panel-list",
  avatarFeed: "ds-avatar-feed",
  feedActionButton: "ds-feed-action-btn",
  feedActionWithCount: "ds-feed-action-count",
  dropdownMenu: "ds-dropdown-menu",
  dropdownMenuItem: "ds-dropdown-menu-item",
  segmentedControlShell: "ds-segmented-shell",
  segmentedControlShellGrid: "ds-segmented-shell-grid",
  segmentedTab: "ds-segmented-tab",
  segmentedTabActive: "ds-segmented-tab-active",
  segmentedTabIdle: "ds-segmented-tab-idle",
  searchStickyHeader: "ds-search-sticky-header",
  inputSearchPill: "ds-input-search-pill",
  tabButton: "ds-tab-button",
  tabButtonActive: "ds-tab-button-active",
  statusPanelDanger: "ds-status-panel-danger",
  statusPanelWarning: "ds-status-panel-warning",
  notificationRow: "ds-notification-row",
  notificationRowUnread: "ds-notification-row-unread",
  notificationSkeleton: "ds-notification-skeleton",
  notificationTypeBadge: "ds-notification-type-badge",
  emptyStateCard: "ds-empty-state",
  buttonDangerSecondary: "ds-btn-danger-secondary",
  notificationStickyHeader: "ds-notification-sticky-header",
  avatarNotification: "ds-avatar-notification",
} as const;

export type DesignRecipeName = keyof typeof designRecipes;
